### PR TITLE
Enhanced Image Augmentation Module

### PR DESCRIPTION
**Pull request by smog-root**
**Closes**: #323 

_**Kindly add level2 for this PR. Review the code and add the label**_ @UTSAVS26 

**Changes:**

**1. `image_augmentation_module.py`**:
        
- Refactored and optimized core image augmentation methods.
        
**Added new features:**

- `add_noise()`: Adds random Gaussian noise to images for augmented variation.
- Enhanced `normalize()`: Better handling for image scaling with NumPy.
- Improved flexibility in handling both OpenCV and PIL images.
- Updated docstrings for each method for clarity.

**2. `usage.py`:**

- Improved error handling for image loading (checks if file paths are valid).
- Enhanced display functionality to show all augmented variations.
- Added automatic directory creation for processed images to avoid manual setup.
- Refined code for consistent and streamlined saving of processed images in different formats.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@smog-root add the test cases file in the test folder.

**Comment by smog-root** [comment]
i have add the test file to the #333.. you can check it

**Comment by smog-root** [comment]
Dude can can you upgrade it to level2??

@UTSAVS26

**Comment by UTSAVS26** [comment]
> Dude can can you upgrade it to level2??
> 
> @UTSAVS26 

Not possible as you are only enhancing the comments of each function.

**Pull request merged**
