### PR TITLE
Documentation files added to all packages in pysnippets

### PR DESCRIPTION
**Pull request by patiltrupti6105**
## Pull Request  Documentation Update Issue #21 

- Adding documentation files for all snippets packages
- **Name** : Trupti Patil
- **GitHub Id** :  patiltrupti6105
- **Email Id** : patiltrupti6105@gmail.com
- **Identify yourself** : Hacktoberfest And GSsoc-Extd
- Closes: #issue_number that will be closed through this PR

##
### Snippet Details

Added Documentation

### CODE REVIEW

**Review by UTSAVS26 — APPROVED** [review]

**Comment by UTSAVS26** [comment]
There is some flaws in the files, but don't worry I change them from my side accordingly.

**Comment by patiltrupti6105** [comment]
Thank you sir

**Comment by UTSAVS26** [comment]
> Thank you sir

I am just a 3rd year engineering student, don't make me sir right now, @SpreadSheets600 please help bro 😭

**Comment by patiltrupti6105** [comment]
Oh I wasn't aware, but I'm in 2nd yr so it still makes sense😭

**Comment by UTSAVS26** [comment]
> Oh I wasn't aware, but I'm in 2nd yr so it still makes sense😭

Hmm 🥲

**Comment by SpreadSheets600** [comment]
> > Thank you sir
> 
> I am just a 3rd year engineering student, don't make me sir right now, @SpreadSheets600 please help bro 😭

She isn't wrong, you are our sir :)
PS when I push, I will update the rest left. Plus let me know what changes you want.

**Comment by UTSAVS26** [comment]
> > > Thank you sir
> > 
> > I am just a 3rd year engineering student, don't make me sir right now, @SpreadSheets600 please help bro 😭
> 
> She isn't wrong, you are our sir :)
> PS when I push, I will update the rest left. Plus let me know what changes you want.

Bro you start too with the sir stuff 🤦
And sure you can update the rest and other changes I listed above i can do it myself, this much I can do as a PA.

**Pull request merged**
