### PR TITLE
Added graphing snippets

### PR DESCRIPTION
**Pull request by DarshAgrawal14**
Fixed Issue : #47 
advanced_graphing is a module  created by integrating :
- matplotlib 
- seaborn 
- scipy 
- plotly
 
#### Key points 
- it is very easy it use as functions have suitable default values , and made using multiple libraries
- Complex graphs can be made easily
- adding feaures such as background , legends etc implicitly

Darsh Agrawal , GSSoC 24 extd Contributor

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@DarshAgrawal14 add the test cases too

**Comment by DarshAgrawal14** [comment]
graphing_example.py is a testing file itself , it shows working of every function using a example test case

**Comment by DarshAgrawal14** [comment]
@UTSAVS26, please let me know if any further changes are needed. Otherwise, I would appreciate it if you could merge the PR.

**Comment by UTSAVS26** [comment]
@DarshAgrawal14 create proper test cases file in `test` folder.

**Comment by DarshAgrawal14** [comment]
@UTSAVS26 Done ! added a test case file in test folder

**Review by UTSAVS26 — APPROVED** [review]

**Pull request merged**
