### PR TITLE
Added Cocktail Shaker Sort

### PR DESCRIPTION
**Pull request by adwityac**
The cocktail_shaker_sort function implements the cocktail shaker sort algorithm, a variation of bubble sort that sorts a list of elements by making multiple passes through the list in both forward and backward directions. This bidirectional approach can improve performance in certain scenarios by allowing smaller elements to "bubble" up to the beginning and larger elements to "sink" to the end more efficiently.

The algorithm initializes the boundaries of the list (start and end) and uses a flag to track whether any swaps have occurred during each pass. If no swaps occur during a full pass (either forward or backward), the algorithm concludes that the list is sorted and exits early. The forward pass moves from the start to the end of the list, swapping adjacent elements if they are in the wrong order, while the backward pass does the same in reverse.

Here is the issue link - [issue link](https://github.com/UTSAVS26/PySnippets/issues/207)

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@adwityac add test cases too in test folder particularly.

**Comment by adwityac** [comment]
@UTSAVS26 Added test cases in the folder

**Comment by UTSAVS26** [comment]
@adwityac why is there Directory.md file?

**Comment by adwityac** [comment]
@UTSAVS26 Actually I'm not sure either. I just made changes to the testing folder and it says I made changed to Directory.md

**Comment by UTSAVS26** [comment]
> @UTSAVS26 Actually I'm not sure either. I just made changes to the testing folder and it says I made changes
>  to Directory.md
>  

Sync your repo once again I have removed it.

**Pull request closed without merging**
