### PR TITLE
Added the implementation of Fractional Knapsack

### PR DESCRIPTION
**Pull request by shuvojitss**
# Fractional Knapsack

### Defination:
This program implements the fractional knapsack algorithm to maximize profit by selecting portions of items based on their profit-to-weight ratio, given a weight capacity constraint. It includes a main program for user input and calculation, along with a unit test to verify the correctness of the solution.

### Input:
```
Enter the number of items: 3
Enter the total weight of the knapsack: 50
Enter the profit of item 1: 100
Enter the weight of item 1: 20
Enter the profit of item 2: 60
Enter the weight of item 2: 10
Enter the profit of item 3: 120
Enter the weight of item 3: 30
```
### Output:
``` The maximum profit is: 240```

### Test Run:
Screenshot 2024-11-09 120241

### CODE REVIEW

**Comment by shuvojitss** [comment]
@UTSAVS26 Please review and approve the pull request.

**Comment by UTSAVS26** [comment]
@shuvojitss branch conflicts

**Comment by shuvojitss** [comment]
@UTSAVS26 Resolved

**Comment by shuvojitss** [comment]
@UTSAVS26 If branch conflict arise again please go to the resolve conflict and then click edit the Directory Structure.md and remove all the lines. Then click mark as resolved and it remove the merge conflict. 
Please 🙏🙏🙏 do it if merge conflict again arises   because I have no other option as for now I have no merge conflict but when you are merging it's getting arised.

**Comment by shuvojitss** [comment]
@UTSAVS26 resolved

**Pull request closed without merging**
