### PR TITLE
AddednumberCheckingfiles

### PR DESCRIPTION
**Pull request by Richajaishwal0**
Have added the folder with python files containing Python scripts that implement functions to check various properties of numbers, including Armstrong, Automorphic, Neon, Palindrome, Perfect, and Strong numbers. Each script provides a simple interface for users to determine the mathematical characteristics of a given number.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@Richajaishwal0 have you raised the issue first?

**Comment by Richajaishwal0** [comment]
Yes it's about adding palindrome, Armstrong checker...

**Comment by UTSAVS26** [comment]
@Richajaishwal0 add the test cases too in `test` folder.

**Comment by Richajaishwal0** [comment]
I have added the test cases too, please check

**Pull request merged**
