### PR TITLE
Implementation of Adjacency List

### PR DESCRIPTION
**Pull request by shuvojitss**
## Problem Statement:

Write a program to store and display a graph in the form of adjacency list.
Let’s assume there are n vertices in the graph So, create an array of list of size n as adjList[n].
- adjList[0] will have all the nodes which are connected (neighbour) to vertex 0.
- adjList[1] will have all the nodes which are connected (neighbour) to vertex 1 and so on.

## Defination
An adjacency list is a way to represent a graph using an array of linked lists. Each index of the array corresponds to a vertex in the graph, and the linked list at each index contains the vertices that are directly connected to that vertex by an edge.

### Sample Input:

Enter the number of nodes in G: 5                        

Enter the number of neighbours of node 0: 2                              
Enter the neighbour 1 of node 0: 1                       
Enter the neighbour 2 of node 0: 2                       

Enter the number of neighbours of node 1: 2                     
Enter the neighbour 1 of node 1: 0                 
Enter the neighbour 2 of node 1: 3                     

Enter the number of neighbours of node 2: 2                    
Enter the neighbour 1 of node 2: 0                  
Enter the neighbour 2 of node 2: 3                      

Enter the number of neighbours of node 3: 3                      
Enter the neighbour 1 of node 3: 2                   
Enter the neighbour 2 of node 3: 1                
Enter the neighbour 3 of node 3: 4                        

Enter the number of neighbours of node 4: 1                  
Enter the neighbour 1 of node 4: 3                                                              

### Sample Output:

The adjacency list is given by:       
```
0-->1-->2
1-->0-->3
2-->0-->3
3-->2-->1-->4
4-->3
```
### Diagrammatic Representataion of the code sample:
```
   0 ---- 1
   |      |
   2 ---- 3 --- 4                       
```
### Test Run:
Screenshot 2024-11-08 215347

### CODE REVIEW

**Comment by shuvojitss** [comment]
@UTSAVS26 Please review and approve it.

**Comment by UTSAVS26** [comment]
@shuvojitss branch conflicts.

**Comment by shuvojitss** [comment]
@UTSAVS26 Resolved

**Comment by UTSAVS26** [comment]
Not resolved.

**Comment by shuvojitss** [comment]
@UTSAVS26 resolved.
I think it's all because of the GitHub commit of directory structure.md

**Pull request merged**
