### PR TITLE
Tkinter for GUI

### PR DESCRIPTION
**Pull request by Charvi-14**
This PR introduces a basic GUI application developed using Python's Tkinter library. The application features a main window with a customizable title, a welcome message, an entry field for user input, and a button that triggers a pop-up message displaying the user's input. It serves as an introductory example of GUI development, demonstrating essential widgets and event handling.

### CODE REVIEW

**Comment by Charvi-14** [comment]
Pls review and close
Regards

**Comment by Charvi-14** [comment]
Could u pls add the labels for the GGSOC24 Extd. and Hacktoberfest
Thanks

**Comment by Charvi-14** [comment]
Pls review and merge

**Comment by Charvi-14** [comment]
Could u add the labels pls
I am a GGSOC24 Extd. Contributor

**Comment by UTSAVS26** [comment]
@Charvi-14 raise this issue again with proper template and full the details there.

**Comment by Charvi-14** [comment]
Done

**Pull request closed without merging**
