### PR TITLE
added the fibonacci generator

### LINKED ISSUE #138: [Feature Request]: Adding a fibonacci sequence generator
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We can generate Fibonacci numbers up to a specified count or maximum value 

Adding a Fibonacci Sequence Generator to PySnippets makes the library more useful by providing a handy tool for a well-known math concept. The generator works efficiently, avoiding slowdowns often caused by recursive methods, which is great for quick calculations. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### Full Name

Kritika Singh

### Participant Role

Contributor at GSSoC'24 ext

@UTSAVS26 can you assign me this?

### PR DESCRIPTION
**Pull request by Kritika75**
This code includes:

1.Fibonacci sequence generation by count or max value.
2.Recursive Fibonacci calculation.
3.Memoized Fibonacci calculation for improved efficiency.
4.Custom start values for the sequence.
5.Fibonacci ratio calculation.
6.Generation as a list or tuple.
7.Sum of the sequence.
8.Fibonacci modulo operation.
9.nth Fibonacci number calculation.
10.Generator for Fibonacci numbers and negafibonacci.

issue fix #138

fibonaaci
@UTSAVS26

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@Kritika75 you need to create test cases file in `Test` folder.

**Comment by Kritika75** [comment]
> @Kritika75 you need to create test cases file in `Test` folder. 

Yeah, sure I'll do it

**Comment by Kritika75** [comment]
hey @UTSAVS26 I've added the test file,please check and let me know, thank you!

**Comment by Kritika75** [comment]
can you pleae remove that pascal triangle commit as i have to create separate pr for that

**Comment by Kritika75** [comment]
@UTSAVS26, is this still under review?

**Pull request merged**
