### PR TITLE
Tksnippets added

### PR DESCRIPTION
**Pull request by lord-cyclone100**
This pr is in response to issue #2  and review pr #6 
pls check now @UTSAVS26 
I have made `.py` files. Also added widget output images in readme.
if u merge pls add hacktoberfest-accepted label
Thanks!!

### CODE REVIEW

**Comment by lord-cyclone100** [comment]
@UTSAVS26 pls close my previous pr and consider this one instead

**Comment by lord-cyclone100** [comment]
@UTSAVS26 
Pls check and let me know

**Comment by UTSAVS26** [comment]
@lord-cyclone100 don't change existing PR_template.

**Comment by lord-cyclone100** [comment]
What do u mean? @UTSAVS26

**Comment by lord-cyclone100** [comment]
I haven't changed anything @UTSAVS26

**Comment by UTSAVS26** [comment]
> What do u mean? @UTSAVS26 

You have changed the PR Template that was created and now in your PR you have changed the actual PR template and use that to raise a new PR.

**Comment by lord-cyclone100** [comment]
Oh sorry
Now i realised.....i for testing purposes i have made the changes....but mistake i forgot to remove them......i will correct ot @UTSAVS26

**Comment by lord-cyclone100** [comment]
@UTSAVS26 pls check now
I have done the changes
if u merge pls add hacktoberfest - accepted label
Thanks!!!

**Comment by UTSAVS26** [comment]
@lord-cyclone100 please fork the repo again and add your tkinter code only, don't change any other file, and then only raise a PR to the main repo.

**Pull request closed without merging**
