### PR TITLE
Features/complex

### PR DESCRIPTION
**Pull request by htanmo**
added more complex functions with better validation and tests.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@htanmo please link the issue number.

**Comment by htanmo** [comment]
@UTSAVS26 it is #17

**Comment by UTSAVS26** [comment]
> @UTSAVS26 it's #17

I have assigned this issue to @SpreadSheets600, you worked on it, why?

**Comment by SpreadSheets600** [comment]
> > @UTSAVS26 it's #17
> 
> I have assigned this issue to @SpreadSheets600, you worked on it, why? 

You can merge it,  he added more operations that aren't there, but make sure he opens up an issue

**Comment by UTSAVS26** [comment]
> > > @UTSAVS26 it's #17
> > 
> > I have assigned this issue to @SpreadSheets600, you worked on it, why? 
> 
> You can merge it,  he added more operations that aren't there, but make sure he opens up an issue

He quotes your issue

**Comment by htanmo** [comment]
So should I open a new issue related to it and reference it or work on a new issue altogther.
@UTSAVS26

**Comment by UTSAVS26** [comment]
> So should I open a new issue related to it and reference it or work on a new issue altogther.
> @UTSAVS26 

Yes

**Comment by htanmo** [comment]
#62 @UTSAVS26

**Comment by htanmo** [comment]
@UTSAVS26 new issue #62 please review and merge it.

**Pull request closed without merging**
