### PR TITLE
Implemented N queen problem

### PR DESCRIPTION
**Pull request by shuvojitss**
### Defination
The N-Queens problem involves placing N queens on an N×N chessboard such that no two queens threaten each other. The goal is to find all configurations where each queen is safe from others in rows, columns, and diagonals.

### Input:
Enter the number of queens: 4

### Output:
```
The 1 solution
. Q . .
. . . Q
Q . . .
. . Q .

The 2 solution
. . Q .
Q . . .
. . . Q
. Q . .
```

### 3 Test Run:
Screenshot 2024-11-08 191837

### CODE REVIEW

**Comment by shuvojitss** [comment]
@UTSAVS26 Please review and approve this. It is w.r.t issue no. #385

**Comment by UTSAVS26** [comment]
@shuvojitss it has branch conflicts.

**Comment by shuvojitss** [comment]
@UTSAVS26 now please see once.

**Comment by UTSAVS26** [comment]
> @UTSAVS26 now please see once.

Not updated.

**Comment by shuvojitss** [comment]
@UTSAVS26 Now review once.

**Comment by shuvojitss** [comment]
@UTSAVS26 Resolved

**Pull request closed without merging**
