### PR TITLE
Updates Tkinter for GUI request

### PR DESCRIPTION
**Pull request by Charvi-14**
This project is a simple graphical user interface (GUI) application developed using Python's Tkinter library. The application serves as an introductory example of creating interactive applications with Tkinter, showcasing essential GUI components and event handling.

### CODE REVIEW

**Comment by UTSAVS26** [comment]
@Charvi-14 add test cases

**Comment by Charvi-14** [comment]
could u elaborate, as far as what the files are about, its along the lines of how to use python lib Tkinter for GUI ,a standard template

**Comment by Charvi-14** [comment]
Review and suggest 
Thanks

**Comment by UTSAVS26** [comment]
From test cases means you need to add test cases file in the test folder like others did.

**Comment by Charvi-14** [comment]
I've Updated it
Check pls
Regards

**Comment by UTSAVS26** [comment]
In the test folder like other contributors are adding.

**Comment by Charvi-14** [comment]
Yep, done
Thanks and sorry for the delay

**Comment by Charvi-14** [comment]
Pls check and verify

**Pull request merged**
